# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
org.gradle.jvmargs=-Xmx6G
org.gradle.daemon=false
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true
## Environment Properties
minecraft_version=26.1.2
minecraft_version_vague=26.1
minecraft_version_range=[26.1, 26.1.2]
neo_version=26.1.2.59-beta
# The Neo version range can use any version of Neo as bounds
neo_version_range=[26,)
# The loader version range can only use the major version of FML as bounds
loader_version_range=[4,)
parchment_minecraft_version=1.21.11
parchment_mappings_version=2025.12.21-nightly-SNAPSHOT
## Mod Properties
mod_id=photon
mod_name=Photon
mod_license=CC BY-NC-SA 4.0
mod_version=26.1.2.1
mod_group_id=com.lowdragmc.photon
mod_authors=KilaBash
mod_url=https://github.com/Low-Drag-MC/Photon
mod_description=Photon is a mod that adds vfx support.
archives_name=photon-neoforge-26.1
## LDLib2
ldlib2_version=26.1.2.39
ldlib2_version_range=[26.1.2.36,)
## KilaGraph
kilagraph_version=26.1.0.14
kilagraph_version_range=[26.1.0.14,)
# Iris - https://modrinth.com/mod/iris
sodium_version=0.9.1+mc26.1.2
iris_version=1.11.2+26.1-neoforge